name: deploy-container

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --force
      - run: npm run build
        env:
          PRODUCTION_DOMAIN: ${{secrets.S3_ENDPOINT}}

      - name: Upload to S3
        run: |
          aws s3 sync /dist s3://${{secrets.S3_BUCKET_NAME}}/container-$(grep '"version"' package.json | sed -E 's/.*"version": "([^"]+)".*/\1/') --endpoint-url ${{secrets.S3_ENDPOINT}}
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.S3_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: 'global'
