name: deploy-marketing

on:
  push:
    branches:
      - master
    paths:
      - 'packages/marketing/**'

defaults:
  run:
    working-directory: packages/marketing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --force
      - run: npm run build

      - name: Upload to S3
        run: |
          aws --endpoint-url ${{secrets.S3_ENDPOINT}} --profile tebi s3 sync /dist ${{secrets.S3_BUCKET_NAME}}/marketing
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.S3_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: 'global'
